// lottie
export const lottie_phone = require('./lottie/phone.json')
export const lottie_lock = require('./lottie/lock.json')
export const lottie_success = require('./lottie/success.json')
export const lottie_phone_img = require('./lottie/phone_img.json')
export const lottie_new_pass = require('./lottie/new_pass.json')
export const lottie_play_video = require('./lottie/play_video.json')

// image
export const banner_intro_ic = require('./imgs/banner_intro_ic.png') // 
export const background_enter_phone_ic = require('./imgs/background-enter-phone-ic.png') // 
export const account_white_ic = require('./imgs/account_white_ic.png') // 
export const close_gray_ic = require('./imgs/close_gray_ic.png') // 
export const back_white_ic = require('./imgs/back_white_ic.png') // 
export const arrow_right_ic = require('./imgs/arrow_right_ic.png') // 
export const eye_open_ic = require('./imgs/eye_open_ic.png') // 
export const account_ic_main = require('./imgs/account_ic_main.png') // 
export const success_main_ic = require('./imgs/success_main_ic.png') // 
export const ic_download = require('./imgs/ic_download.png') // 
export const ic_white_close = require('./imgs/ic_white_close.png')
export const ic_main_camera = require('./imgs/ic_main_camera.png') // 
export const ic_date = require('./imgs/ic_date.png') // 
export const eye_close_ic = require('./imgs/eye_close_ic.png') // 
export const img_empty = require('./imgs/img_empty.png') // 
export const edit_icon = require('./imgs/edit_icon.png') // 
export const ic_logo_huvang = require('./imgs/ic_logo_huvang.png') // 
export const ic_intro1 = require('./imgs/ic_intro1.png') // 
export const ic_intro2 = require('./imgs/ic_intro2.png') // 
export const ic_intro3 = require('./imgs/ic_intro3.png') // 
export const ic_logo_ginto = require('./imgs/ic_logo_ginto.png') // 
export const cmnd_ic = require('./imgs/cmnd_ic.png')
export const deposit_to_invest_ic = require('./imgs/deposit_to_invest_ic.png')
export const line_ver_gray_ic = require('./imgs/line_ver_gray_ic.png')
export const line_ver_main_ic = require('./imgs/line_ver_main_ic.png')
export const note_main_ic = require('./imgs/note_main_ic.png')
export const logo_payme_ic = require('./imgs/logo_payme_ic.png')
export const security_ic = require('./imgs/security_ic.png')
export const success_ic = require('./imgs/success_ic.png')
export const tutorial_take_CMND1 = require('./imgs/tutorial_take_CMND1.png')
export const tutorial_take_CMND2 = require('./imgs/tutorial_take_CMND2.png')
export const tutorial_take_CMND3 = require('./imgs/tutorial_take_CMND3.png')
export const camera_ic = require('./imgs/camera_ic.png')
export const background_identify_result = require('./imgs/background_identify_result.png')
export const logo_ginto = require('./imgs/logo_ginto.png')
export const success_white_ic = require('./imgs/success_white_ic.png')
export const video_tutorial_1_ic = require('./imgs/video_tutorial_1_ic.png')
export const video_tutorial_3_ic = require('./imgs/video_tutorial_3_ic.png')
export const video_tutorial_2_ic = require('./imgs/video_tutorial_2_ic.png')
export const video_tutorial_4_ic = require('./imgs/video_tutorial_4_ic.png')
export const face_straigth_ic = require('./imgs/face_straigth_ic.png')
export const face_right_ic = require('./imgs/face_right_ic.png')
export const face_left_ic = require('./imgs/face_left_ic.png')
export const support_main_ic = require('./imgs/support_main_ic.png')
export const tutorial_video_1 = require('./imgs/tutorial_video_1.png')
// export const tutorial_video_2 = require('./imgs/tutorial_video_2.png')
// export const cmnd_back = require('./imgs/cmnd_back.png')
// export const cmnd_front = require('./imgs/cmnd_front.png')
export const back_black_ic = require('./imgs/back_black_ic.png') // 
// export const document_info_user_ic = require('./imgs/document_info_user_ic.png') // 
// export const ic_logo_main_ginto = require('./imgs/ic_logo_main_ginto.png') // 
// export const ic_main_setting = require('./imgs/ic_main_setting.png') //
// export const status_confirm = require('./imgs/status_confirm.png') // 
// export const status_documents_success = require('./imgs/status_documents_success.png')
// export const status_documents_err = require('./imgs/status_documents_err.png')
// export const status_un_confirm = require('./imgs/status_un_confirm.png') // 
// export const arr_right_white_ic = require('./imgs/arr_right_white_ic.png') //
// export const camera_white_ic = require('./imgs/camera_white_ic.png') // 